# Jersey colour classification in football video

In [1]:
import torch
import pandas as pd
import numpy as np

from dataset import load_manifest, get_loader
from models import load_model
from extract_embeddings import get_embeddings, extract_all_models
from classification_clustering import compare_models
from visualization import interactive_embedding_view, plot_confusion_matrix

c:\Users\Denis\OneDrive\Документы\sk_sber_football\.venv\Lib\site-packages\torchreid\reid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
from pathlib import Path

manifest_path = Path("dataset_v1/manifest_with_splits.csv")

if manifest_path.exists():
    df = load_manifest(manifest_path)
else:
    print("dataset_v1/manifest_with_splits.csv not found, fallback to ../dataset/manifests/*.csv")
    manifests_dir = Path("../dataset/manifests")
    parts = []
    for split_name in ["train", "val", "test"]:
        p = manifests_dir / f"{split_name}.csv"
        if not p.exists():
            continue
        part = pd.read_csv(p)
        if "split" not in part.columns:
            part["split"] = split_name
        parts.append(part)

    if not parts:
        raise FileNotFoundError(
            "No manifests found. Expected dataset_v1/manifest_with_splits.csv or ../dataset/manifests/{train,val,test}.csv"
        )

    df = pd.concat(parts, ignore_index=True)

    # Convert detection-level manifest to the format used by this notebook.
    df["crop_path"] = df["image_path"]
    df["game"] = df["source_folder"]
    df["label"] = np.where(
        df["role_name"].astype(str).str.strip().str.lower() == "goalkeeper",
        "goalkeeper",
        np.where(df["left2right"].astype(int) == 1, "team_left", "team_right"),
    )

print("dataset size:", len(df))
df.head()

dataset_v1/manifest_with_splits.csv not found, fallback to ../dataset/manifests/*.csv
dataset size: 65356

,frame_idx,image_file,player_id,jersey,role_id,role_name,x1,y1,x2,y2,...,vx,vy,left2right,source_folder,image_path,player_global_id,split,crop_path,game,label
0,1877,frame_001877.jpg,101,5,3,Left Central Back,1399,522,1475,667,...,0.125926,-0.003292,1,game_10_H1,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1_pid101,train,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1,team_left
1,1877,frame_001877.jpg,105,20,6,Left Midfielder,77,549,126,704,...,0.088889,-0.107819,1,game_10_H1,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1_pid105,train,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1,team_left
2,1877,frame_001877.jpg,106,21,11,Right Winger,185,169,223,269,...,0.155556,0.072428,1,game_10_H1,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1_pid106,train,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1,team_left
3,1877,frame_001877.jpg,107,22,13,Right Back,285,133,312,189,...,-0.078189,-0.099588,1,game_10_H1,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1_pid107,train,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1,team_left
4,1877,frame_001877.jpg,110,99,7,Right Midfielder,1242,152,1305,260,...,0.177778,-0.071605,1,game_10_H1,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1_pid110,train,c:\Users\Denis\OneDrive\документы\sk_sber_foot...,game_10_H1,team_left

In [4]:
df["game"].unique()[:20]

<StringArray>
['game_10_H1', 'game_10_H2', 'game_11_H1', 'game_11_H2', 'game_12_H1',
 'game_12_H2', 'game_13_H1', 'game_13_H2', 'game_14_H1', 'game_14_H2',
 'game_15_H1', 'game_15_H2', 'game_16_H1', 'game_16_H2', 'game_17_H1',
 'game_17_H2', 'game_19_H1', 'game_19_H2',  'game_1_H1',  'game_1_H2']
Length: 20, dtype: str

## game_12

In [5]:
base_game = "game_12"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 722 H2: 697 Total: 1419

In [6]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_right    682
team_left     641
goalkeeper     96
Name: count, dtype: int64

In [9]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["dino", 'osnet']
)

========================================
  модель: dino
========================================

c:\Users\Denis\OneDrive\Документы\sk_sber_football\.venv\Lib\site-packages\timm\models\_factory.py:138: UserWarning: Mapping deprecated model name vit_base_patch16_224_dino to current vit_base_patch16_224.dino.
  model = create_fn(

loading cached embeddings
  готово: shape=(1419, 768)

========================================
  модель: osnet
========================================
Successfully loaded imagenet pretrained weights from "C:\Users\Denis/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
loading cached embeddings
  готово: shape=(1419, 512)

c:\Users\Denis\OneDrive\Документы\sk_sber_football\.venv\Lib\site-packages\torchreid\reid\models\osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)

### Metrics

In [ ]:
df_report = compare_models(embeddings)

df_classification = df_report[[
    "lr_accuracy",
    "lr_macro_f1",
    "mlp_accuracy",
    "mlp_macro_f1",
    "macro_f1_delta_mlp_minus_lr",
    "best_lr",
    "best_mlp",
]].copy()

df_clustering = df_report[["cluster_acc", "cluster_macro_f1", "sil_euclidean", "sil_cosine"]].copy()
df_clustering = df_clustering.rename(columns={
    "cluster_acc": "kmeans_acc",
    "cluster_macro_f1": "kmeans_macro_f1",
    "sil_euclidean": "kmeans_sil_euclidean",
    "sil_cosine": "kmeans_sil_cosine",
})

print("Classification comparison: Logistic Regression vs 2-layer MLP")
display(df_classification)

print("Clustering metrics (k-means)")
display(df_clustering)

evaluating dino...
evaluating osnet...
Classification metrics

       accuracy  macro_f1 best
model
dino     0.9613    0.9383    +
osnet    0.9401    0.8788

Clustering metrics (k-means)

       kmeans_acc  kmeans_macro_f1  kmeans_sil_euclidean  kmeans_sil_cosine
model
dino       0.4743           0.3533                0.0843             0.1559
osnet      0.7491           0.6136                0.0921             0.1689

### Visualization

In [12]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1419 точек...

c:\Users\Denis\OneDrive\Документы\sk_sber_football\.venv\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_12_H1', '692', '101',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_12_H1', '692', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC5r+sz6DpaXP2vSf3hEFqEniuA0hJO5jESVHGM+tM0HUNe1l1aU6NZQrKY7tp5PKZz3MYY5kHvwPSsJLaARhRbxAdcKgGPeorm1VCpi3uPLBfI6HvShnHLBr2ad/vM513o9TqfiD4o8O2NxPa6Bc3d7qVs6q7XS/6MFxkspUfOeVx71nHxEVkjF1q+k6hC0SpHFZJL54lOAMjYFC55Jzn0rGt5fL4Iyv6ippgk6fNlh9amnnaUOVU0/XcynUlNNczV/P8A4Bv2fi7SmuLRBe3cUVvHJGf+JdKx5OQSVTPGOn4dKy7nxTAbz7GNLuxYyDe16YWdxJg87H25B44BGM9ayJIZIjuQsR6g80qTuRiRN49e9c7zaV/hSFCtKEVG7fq9S34g8V6iZmj0DTJLqKVcySXKi3IbkY2B2B47nFJqfiK++w5tdInN7HlIZZ3jVUTGBnaSWPJ68c1WEdvJnapB9Qf6UpS6Rd0bK6D1H6c1lLNa3ZD9vNF2w1G0vNHnk1SBotTZXRFs5okG09OWU4I5HcYqK3kvbqK7k1C5SwEUebaG1sZLuIgkM5bd8ykFUIYluTjp1ovLC2RNGqt7LUlnNPbPvsdQuLc/9M2xx9KiGcTTtJJjjiHe7KKQ30mjLfXiW9rAGJnWViJIMuq7tnIfO4EYOcA9MVMlhfvpkOoQ6ZqP2ETuPtr2xaJMdsrnacHHp8wq9cXlxO4a+jh1BQhQpIgUMD3IGMkHkGrlpqEGmwPpiz3ItnDNcBZWaG4YjIO3Ixg46dx2ruhmmHlu7f19xusXpqyO3lR4wSCD0ODUsqtGoKuWWVCOODjoR+lZdpcrDIP3YfPZzkH8OKtzXLzyGSQKCRgADAA9AMnA9K8KnVTVupx9CCWMxtgnjsabG+w5DcelTtiRNrVQm3Qv15HI96yneLuhGlHJFIOG59KNkaypMg+dGDD04NZKSuDuYgN7cVct7lJXEckioT/ExwBVxqpvzEMOEd/tC7AFJjdFJ3N1wefrz9KVL5lG1gHX0NT3DQCVlR/NjPKseMg+o9apTRjrHx7UqvMnp0BlsTwSrgKPoailiGMxkqf9rkVntIVOCMGnG8YE/L8vpnOPxrmlOEtJIkmdrtBngr69RTRcMBhgFH+zyKRLtGORv3f3V4Y+w96YZY5eTHjIz6EfWp9m7Xix20uNV+OTV6CXegO7kcGqGmxrdXkdvJOtshDFpTGX24UkcD1OB+NRWk7jaW4LAZHoadNuNn0ZRr+YMVHIyyKVI/8ArVX3kd6C4xnOK6L33Fcgk3K21utJn1P5VKyiVlReWJwKqNJtYggZ9mBH5jg1zyp8uvQTT3LsVxgbWyR61NvBHrWUZT6CnR3Lr1OR6VUattGK5oOquMMoIqvJEU5XkfrSCbI3A8UF8+9VKKkDIHdD3ApvnFe+RUzWss33IJCfVUNRvpuoDrbMB6kgVk6dRaoVmMtb24tXMltPLCxG0mNtpI9KjedncuzMzsdzMepPrRRUR2NCdJdybjnJpwlBU8GiiuqOwiO4kJjZFeRCwI3o21l9wfWprezluIxtdAUGMnPYUUVb1STH0JotKJGXuMeyrTnsLSFGeRpnC8nnFFFDpxTWgKKIPDuoaVqGvx6VaWkiTNC82+VQV2oQCOp5ya2LHVbOTW/7LjgdHDspdUUAbRnNFFe5h8LScb2N4xRS1XXzHeTwwKfLVF2NIuW3biGyAQMccVjarqt9dWSxwyYdpcGT/V7dylQAF5IDENyewooqasYwl7qX3IuyR//Z'],
                                   ['team_left', 'game_12_H1', '692', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC5r+sz6DpaXP2vSf3hEFqEniuA0hJO5jESVHGM+tM0HUNe1l1aU6NZQrKY7tp5PKZz3MYY5kHvwPSsJLaARhRbxAdcKgGPeorm1VCpi3uPLBfI6HvShnHLBr2ad/vM513o9TqfiD4o8O2NxPa6Bc3d7qVs6q7XS/6MFxkspUfOeVx71nHxEVkjF1q+k6hC0SpHFZJL54lOAMjYFC55Jzn0rGt5fL4Iyv6ippgk6fNlh9amnnaUOVU0/XcynUlNNczV/P8A4Bv2fi7SmuLRBe3cUVvHJGf+JdKx5OQSVTPGOn4dKy7nxTAbz7GNLuxYyDe16YWdxJg87H25B44BGM9ayJIZIjuQsR6g80qTuRiRN49e9c7zaV/hSFCtKEVG7fq9S34g8V6iZmj0DTJLqKVcySXKi3IbkY2B2B47nFJqfiK++w5tdInN7HlIZZ3jVUTGBnaSWPJ68c1WEdvJnapB9Qf6UpS6Rd0bK6D1H6c1lLNa3ZD9vNF2w1G0vNHnk1SBotTZXRFs5okG09OWU4I5HcYqK3kvbqK7k1C5SwEUebaG1sZLuIgkM5bd8ykFUIYluTjp1ovLC2RNGqt7LUlnNPbPvsdQuLc/9M2xx9KiGcTTtJJjjiHe7KKQ30mjLfXiW9rAGJnWViJIMuq7tnIfO4EYOcA9MVMlhfvpkOoQ6ZqP2ETuPtr2xaJMdsrnacHHp8wq9cXlxO4a+jh1BQhQpIgUMD3IGMkHkGrlpqEGmwPpiz3ItnDNcBZWaG4YjIO3Ixg46dx2ruhmmHlu7f19xusXpqyO3lR4wSCD0ODUsqtGoKuWWVCOODjoR+lZdpcrDIP3YfPZzkH8OKtzXLzyGSQKCRgADAA9AMnA9K8KnVTVupx9CCWMxtgnjsabG+w5DcelTtiRNrVQm3Qv15HI96yneLuhGlHJFIOG59KNkaypMg+dGDD04NZKSuDuYgN7cVct7lJXEckioT/ExwBVxqpvzEMOEd/tC7AFJjdFJ3N1wefrz9KVL5lG1gHX0NT3DQCVlR/NjPKseMg+o9apTRjrHx7UqvMnp0BlsTwSrgKPoailiGMxkqf9rkVntIVOCMGnG8YE/L8vpnOPxrmlOEtJIkmdrtBngr69RTRcMBhgFH+zyKRLtGORv3f3V4Y+w96YZY5eTHjIz6EfWp9m7Xix20uNV+OTV6CXegO7kcGqGmxrdXkdvJOtshDFpTGX24UkcD1OB+NRWk7jaW4LAZHoadNuNn0ZRr+YMVHIyyKVI/8ArVX3kd6C4xnOK6L33Fcgk3K21utJn1P5VKyiVlReWJwKqNJtYggZ9mBH5jg1zyp8uvQTT3LsVxgbWyR61NvBHrWUZT6CnR3Lr1OR6VUattGK5oOquMMoIqvJEU5XkfrSCbI3A8UF8+9VKKkDIHdD3ApvnFe+RUzWss33IJCfVUNRvpuoDrbMB6kgVk6dRaoVmMtb24tXMltPLCxG0mNtpI9KjedncuzMzsdzMepPrRRUR2NCdJdybjnJpwlBU8GiiuqOwiO4kJjZFeRCwI3o21l9wfWprezluIxtdAUGMnPYUUVb1STH0JotKJGXuMeyrTnsLSFGeRpnC8nnFFFDpxTWgKKIPDuoaVqGvx6VaWkiTNC82+VQV2oQCOp5ya2LHVbOTW/7LjgdHDspdUUAbRnNFFe5h8LScb2N4xRS1XXzHeTwwKfLVF2NIuW3biGyAQMccVjarqt9dWSxwyYdpcGT/V7dylQAF5IDENyewooqasYwl7qX3IuyR//Z'],
                                   ['team_left', 'game_12_H1', '692', '107',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC5r+sz6DpaXP2vSf3hEFqEniuA0hJO5jESVHGM+tM0HUNe1l1aU6NZQrKY7tp5PKZz3MYY5kHvwPSsJLaARhRbxAdcKgGPeorm1VCpi3uPLBfI6HvShnHLBr2ad/vM513o9TqfiD4o8O2NxPa6Bc3d7qVs6q7XS/6MFxkspUfOeVx71nHxEVkjF1q+k6hC0SpHFZJL54lOAMjYFC55Jzn0rGt5fL4Iyv6ippgk6fNlh9amnnaUOVU0/XcynUlNNczV/P8A4Bv2fi7SmuLRBe3cUVvHJGf+JdKx5OQSVTPGOn4dKy7nxTAbz7GNLuxYyDe16YWdxJg87H25B44BGM9ayJIZIjuQsR6g80qTuRiRN49e9c7zaV/hSFCtKEVG7fq9S34g8V6iZmj0DTJLqKVcySXKi3IbkY2B2B47nFJqfiK++w5tdInN7HlIZZ3jVUTGBnaSWPJ68c1WEdvJnapB9Qf6UpS6Rd0bK6D1H6c1lLNa3ZD9vNF2w1G0vNHnk1SBotTZXRFs5okG09OWU4I5HcYqK3kvbqK7k1C5SwEUebaG1sZLuIgkM5bd8ykFUIYluTjp1ovLC2RNGqt7LUlnNPbPvsdQuLc/9M2xx9KiGcTTtJJjjiHe7KKQ30mjLfXiW9rAGJnWViJIMuq7tnIfO4EYOcA9MVMlhfvpkOoQ6ZqP2ETuPtr2xaJMdsrnacHHp8wq9cXlxO4a+jh1BQhQpIgUMD3IGMkHkGrlpqEGmwPpiz3ItnDNcBZWaG4YjIO3Ixg46dx2ruhmmHlu7f19xusXpqyO3lR4wSCD0ODUsqtGoKuWWVCOODjoR+lZdpcrDIP3YfPZzkH8OKtzXLzyGSQKCRgADAA9AMnA9K8KnVTVupx9CCWMxtgnjsabG+w5DcelTtiRNrVQm3Qv15HI96yneLuhGlHJFIOG59KNkaypMg+dGDD04NZKSuDuYgN7cVct7lJXEckioT/ExwBVxqpvzEMOEd/tC7AFJjdFJ3N1wefrz9KVL5lG1gHX0NT3DQCVlR/NjPKseMg+o9apTRjrHx7UqvMnp0BlsTwSrgKPoailiGMxkqf9rkVntIVOCMGnG8YE/L8vpnOPxrmlOEtJIkmdrtBngr69RTRcMBhgFH+zyKRLtGORv3f3V4Y+w96YZY5eTHjIz6EfWp9m7Xix20uNV+OTV6CXegO7kcGqGmxrdXkdvJOtshDFpTGX24UkcD1OB+NRWk7jaW4LAZHoadNuNn0ZRr+YMVHIyyKVI/8ArVX3kd6C4xnOK6L33Fcgk3K21utJn1P5VKyiVlReWJwKqNJtYggZ9mBH5jg1zyp8uvQTT3LsVxgbWyR61NvBHrWUZT6CnR3Lr1OR6VUattGK5oOquMMoIqvJEU5XkfrSCbI3A8UF8+9VKKkDIHdD3ApvnFe+RUzWss33IJCfVUNRvpuoDrbMB6kgVk6dRaoVmMtb24tXMltPLCxG0mNtpI9KjedncuzMzsdzMepPrRRUR2NCdJdybjnJpwlBU8GiiuqOwiO4kJjZFeRCwI3o21l9wfWprezluIxtdAUGMnPYUUVb1STH0JotKJGXuMeyrTnsLSFGeRpnC8nnFFFDpxTWgKKIPDuoaVqGvx6VaWkiTNC82+VQV2oQCOp5ya2LHVbOTW/7LjgdHDspdUUAbRnNFFe5h8LScb2N4xRS1XXzHeTwwKfLVF2NIuW3biGyAQMccVjarqt9dWSxwyYdpcGT/V7dylQAF5IDENyewooqasYwl7qX3IuyR//Z'],
                                   ...,
                                   ['team_left', 'game_12_H2', '139259', '104',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDCn0ye7tXaGCKOVJEIJJ8rdgYDADgHpk/Q1BeaNqOn6xbW91qCbQf3slvKksca552ZPQEkHOP4sdc1250fwzb6FbWNzqN699PbmWTyWJ2lclYwuAhPY5zznHFZ9pe6Uun6WJ1b7TphjkiksreOGSZwuGaWXqSOMYBHGcV3QxMKEGpOOvfV/KxNWpFu6L3iTR9LeFbvwhb63PrGCJF1FVRGjB+ZgqjLHBB446+lZNsbi11422ptYwK9s37n51lD8H5hg4XjOevSmS+Ir1Y3t7OeW3tyz7FVhvCsc7S+AT/L2rML3ErljI+5urFiSa5YZ1Rppw5b+dtfzOapUvezav5/8A3NR1W3k1CCK3utNa3VmVmmnwGbcuMdOAuemeTV9Rp9pcJHc3iQHG5o2+QMRxwGIyMZwB6c81yYiSJcFgSDkLgdfX2rROtaxLb21vLcLNDaoI4BcQpKY1BzgFgT196U84oNJWf3f8EqlWdONnd+ru/0OouY7Sz3TwtbHCfI7MqksT6EYPfj9adpdtbE+S9ydhw8kizZYkDLkZ7Dvzg56nFcrf399fz3NxfXMlzJcEtNvAKnIwQF6AewAFRXGoX93brZT3UstsNoSKUlkTAwMDtx6UPNMP3f3f8ABNPrT7HZPFBJcxm2FqkisisN5dtvrxkH9Ov0pgH7xZZJopExl5CdrE55+XkKvHTjp71y1leNFK811a2l9I1ulshuUZvKjXPypgjGc8nr09Ku+IvEd1qumLbSWmmxZnjnEtvDslRkPAyP4TjkHg1X9o0F10H9aVtjYULZ6PFMJY42EhZleTaG3sMNnPB49DWlcwaZZ2MMMD28cc6eWyn/AFY38hM57cnpXDaXqFzbRssUdsFPBMkKyk9OCXzkfKP8k1BpccmnTzXUE8xkbfI4eQtGSTk/uydg9OBwKpY7DvVT/B/5C+tL+UghupkkWWGTy3U5Vu4pVVpOSwYDuTxVXz4v4FJ92/wo3GRh87ZHrXyHNG5zF0eSvBYE+g/xqSNwCCqDH5A/XuaqKoBHzU4sF7gmqU7CJwiA/dHWlJwduAMGqbuzAg9PQGnJvOOwA6Cp9otkBcfy5EjUR7WUEM2fvHPX9cUqKFIVAGJOOTz+FRI7phlZlI5BBwRUUs4IKlySeuR60+fW7BFiQj7uee9OdfKVoWfgkMwA4z25/GqayYHXNTwSsQMhWUdA3akql2IsqqIoC4IxkEHr71LBE88VwscZdhETgZz1Gf0qsXjx/qyv0apICjQSqHZC7RoGPQZauiEk3YDAUKuOKeGFXNNg0rVLoQWOpTJhS0jTWrjaMcdhnLbRx603+yrjyhIZox8uSewI68+1YSw9aKu4mvs5diAPk4zimlgFbDfiTU40q/YZiRJR6xvmp57G7/s+3U2LpNEzq+2MZYHBBJH3u455GKzVNyTv0IaZnwhwxYt945PJ9P0q15jY6ioJY5o/9ZFIv1UiqGn37XRug0LQ/Z7hoRls78Y+YfnQouzb6EmoZ9o560zzkB+dWJI6pjj659+1VixJz/WjOerVnzu4XLIlz2q0jqEAqhEcPk8AVMGX604aagWWb0p7Ef2ZMT3lQfo1Uy4zwTU0j/8AEpYk9ZwOvop/xq+bcDOeXTtK8QlLCze2ebT0mMsD+Wdpb5kKjryAc57dKigjTV01GN9U1b7PdkxzW7yqUPGGxxn5g2CetFFfQP3YprQ6ac5Nbiz+F4oNQTV1uWEz2xiRAuIxGBsUlVwN4HGe3Hfmr8HiPU7TRLWErBK1pbiPzcYabaMZfIbJ460UVE5yU7X00LlobWi+JxqOmRXT6fHEzgpt8wuuQAS3bB5Ht1pIk05i7NZD52JfBxub1/z1oorLGJKpJLuyIq6TY37BpMhC+TKhI5K46/mKa3h6B1jaKaRN6lhnnGOtFFcfsoPdClCPYj/sCUIGjulPfDJWBf3a2evRaS6kzSW5nDD7uAcY9c0UUp0oRWiMmkO88E9CKsSyj+yBnOTcH/0CiiuOOt/Qjof/2Q=='],
                                   ['team_left', 'game_12_H2', '148264', '104',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDjNVutTnunmsbqPTwYyNlsn+sbjDSM5bcevQDOa3NN1u/CWUMsSwgJsuLhC+8fLtBQB/xIwBWbFCqjkLkd6kwQPlAP1NcMM5rxhyNRfnbX8LHD7Sd73Ot8Ran4YsNHx4Zl1m/1F5CA2ov5aRRk842AZOeee5+lYGn6tdyX0i30ztD5OYZQvzxSjoAORtPf6A1RWMseg/OplQKOAPzpwzqtGPLyxfnZ3/MmcpyTXM16Gpd6wIbiFrVGkiVf3jHCM/zghen93Jzg84wMZqjBrl/DcKwBnR3JlRX8hiv8ADYfpx2Gcdu1ZlMjYUEgU+G3KnexAHYZ5pPN682moqy8n+Oo6c5wjy8zfruT3+o6w+9NLuvstuWCLbXUjTllOdz+YApU8KAuD1JzWjqWvRzWgW2gvbaZTtMv2repUZwCuBnB9x6d6oRBfOQEEgsM/nVWcL5kgUsFLHHfjNQ8yrJX0NHXmT6NqV9aKRdRyXLxh/s7wXxtlCsQQpTY+ADk5DH2AqtFe30WoWTahcPf2kSmSaISNExkP3QGySVXjnjdzwKmtVV1YF1XapIz39qbPCcYIIOMiiWZ13FNWJ9tIs3upi4aGOwSWxt4kIMRl84segOW6YHGPeorbV9StdNeFrSxmuAu2K4M1xkfe5ZQ4BIzx79c1S2lT05pwbcNrdamOa19dV9wvayZEJCcbmJPqe9SI2e5xVaMcAknH1p5kRMlmIAryVJvclalsOoHU0jyDoG5qK5BgERLAiWJZUIxyrDI+n0quXJyeTjknHSnUbg3F7g9C5E7bZACCu35hnHGe1TKyNh2d9wULlhngdBWe4glMBRWDKuWJx97nJHtjFWQQP4hTUrbBcuQBjJHIHXYZQuffg49aq3EpkuJHeUMzOSTjrz7CltSpuIMOufNXIzyOR/n8Kqyn94+GH3j/OipJWTsJ3RYRwrAliR3AFTNPI0aK+35R1C4BPc1mBz2IzVsztIqZ2AKgUbRj8T70Qq+60Fx0zZG4cevFVml461KznpniqtwCvzA8Gs5PqIiVxjG6mF4nBO4EZIqXTrKS5vY4Jme2jYMWlaFnAwpI4HqQB+NZsk90LZri9DYijy7LGwCqq+/PY+9PkfLcrl0uW1YD1HpTo53jkR41yVIbB6HBzzVOwmW+s4ry1DywTKGRwp5FWAsveGT/vg1naSl5olltZRJI8ip5aliQuc49qkDHHLc1AkcoAHkyj/gBpokIkaLB8xQGK45APfFaO71YF2xwbyAjqZF6fUVWkkxI2D3PU0+wZjfW4Ib/Wr296pyuPMYdOT1qZJ8oNkrS4zzViSWESbLdyyBVJJ9SMkdBwDkf41QLoByR60gmAfhhzSjNxTj3EXTK3fFMZyVIIzS6dCNQvVs7aSNZyMkzyiOMccDceB+fORVeQkMRkZBx1obs+W+v+ZUotbnVRa9cRzNJEfJLLtPlrjj86o6hqPnW8iNEjM6MpZkByWBGT69aKK9ZQTO1lbQpl0/SLXT44oglsgQbUHb+ladgL/XdXsNA0qaC0vdSvEt45pYsrGSrNnjkfdx0PU0UV0YanF1U2gSTZ6zp3wgvodHuY73xBPdag6Okc6yCOOFxwGCeWdw3AggnlTkYNeVa74T1LwR4tZ9ev4b7V7yzXL265iWJWwOqq24kc9sAUUV0YtJU9FbUckkjZ8QW50X4bxeLbi5LvexXDWNukIK74c5ErbgQpwPu5NVtNso9W+Ftp48tZz5Es0dvNbSw7WSZk3NtIY5QHgZwfWiis50Yew5rai5VY5HVtVlt7uBFht/LkHzFotxHOPUZ+laTxWlzaXd1Zzo4ghaYJNpwQsB2yJTj8qKK6MNh6U6MXJasUYpozdKudO1nQy1xpFpIxkKTRypvibbgrx1yAR1PWtErpTBs2eFxxhRnP50UV5OKhGFaUYrQTimf//Z'],
                                   ['team_left', 'game_12_H2', '148775', '104',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA2AGADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDF17UYo9OjdJbmzulUyJE0KyB/7pL5IVcKQcAdBUOi6ousta2cU1s8aIHufsyuxRScKQoznJYdcZz71nqbp0aNrqfY4IZN5IbPXI70kcMVq8LphZIVKxFeDGD1Ax0HtUU87jFNOF0++69NTGWIT11R3PjnVvCGjEDR7m5g1veGaHWikKeVg8gY3c9uRz9Kr2UWqx3Jlvmjh0+O3LCUxvkPtyA3ykFMEjOD0Fcs91eTEh5C+Rg71DcfjmmQ26qLfc7sLfPlAuxC569TyPY8VrDPYRhyKF/N7/mZzqKaacmr9jp4ZhPfeXpLefbuwNw6M2EIYYAVcbfk56HnHbNaMl5ZOhsUcSK8brsCjLICMjqMDnpkk+hxXMW+sX9m8r2d28MkpDStGFXeQMAtgckDjms62FzHereQXVzFdCUzfaVmYSbj1y3Ug+nSied0nZKP9feFKqqceW7fqdjbJbypLM2oS3MPlqNhkBxg8gtuB5zyO9SzXFvteRrmNh8wCqAeowAOhHPt61y+nuNPnjubKC1tp4iCskUCqwI3YOQOo3t/30ao6w13qk0Ul1qV/J9nk823/wBIIEDdyn93NR/a1K13c1+sqx19xNptnZRKL6CK6jKs7wvk7TjqmDyNvJz+HpsS61pL6RGbR4ZJQRJdTxtkyPIRtyoUDONufy964HRbjWbC1a2ste1S1g3bxGlwMbjjkDHXgVn/APCPwzax/aT3+om+efzmn+0fP5mc7vrnmmsyovVXH9ZXY72S+s7VZjBqdvDbSkvIchGTgfLkDjOBgdTjqKij1m10v5UuRDbwwCRDJlRKAv8Ae4y245+YcgE+lcxNf+ILmyltp/FGsyQSj542nGD09vYVlaTpbafqravY6pqdvqGWJuEn+f5s7uSO+TR/alC5LxF0XpFGxQjYP8QU8e3NCwjHOTTUcADKj8DQZRyOlfMto5SYYUUMCRycfhUO9c9ealKMu0uCAy7hg9RRzN7BYVUYnOAV/Kp1YrEYgF2lt33ec9P8ioEKruO5stz1NK0m3BDkHqKalYB0m4kpgg9wRTZLcoQH2gkZxnJ/TpSSTyvcGdpC0hbcWPUn1pPPhklwwdGPzbgMr9KV1JuwrFrykgASTcrkAhSuCQRnNWIkiE8BV94YbjjGVPoaqkDqHi/l/OrcMEkN5EudxaPf0x1U9PX61vTTavbsN26GWNu3qenpSxYD4DDnjkVL5SnTvtAbMgmCFM87SuQcfUHmq4YbSpDb+oP8OO+T69MVg4tMSVymTu6s1L1HVqZp0C3V8lu9yLdGDFpDGX24UkcDnk4H41HAX2KzDDkDI9DWFpNXCxbRT3JFLEgjB4KlzuOQcntn6H/CofMbHBqOJnjHzSu47FjnA9K1i0kwWxeLbRkkVFuJOcjNV3lcgMQ4U/dyuAfp603zD3NZzvsK5bLZHOPzqaPITOMkmqKMScVYEuAB6URTC5YLcdKnsVeW4EpUsqIwZiScfIcD/wCtx7VQ8wHjNXdLupULwJIBG6SFhjqdh5/DHHpzW9JrnXMBnFhgZHSm7n3DDEL3UHg/Wmh8gc9KTcc9vWubmaBOxDZXc9o5ktppYXYYZo2Kkj0+lJJMWZnYszMcsSckk96KKroMb52AetRyXAHHzYoopMTLt9cxS2NntM3mRRqrbmypDZIxk8dDx0qmsn1oorSs3KV35A0S28gyTzxU/mgetFFStgBpQCOD1xVnTZAbkjnmOT/0BqKKcfiQIzmlB55pGkwO5NFFc9xH/9k=']],
                                  shape=(641, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': 'f3b803a0-799f-4dff-a201-81a632b6d521',
              'x': {'bdata': ('IQiwQFpNtEDROutAh+nHQMKHi0BY37' ... 'hA1gK3QEa2oUAdQJxAx6SuQLmzykA='),
                    'dtype': 'f4'},
              'y': {'bdata': ('fWrswCalDcEOht7ANUHnwJEmsMD85t' ... 'DBASKwwH9uysDE57zArT3WwPSi28A='),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_12_H1', '692', '200',

## game_50

In [10]:
base_game = "game_40"
df_h1 = df[df["game"] == f"{base_game}_H1"].copy()
df_h2 = df[df["game"] == f"{base_game}_H2"].copy()

print("H1:", len(df_h1), "H2:", len(df_h2), "Total:", len(df_h1) + len(df_h2))

H1: 765 H2: 726 Total:

 1491

In [11]:
def flip_lr_label(label: str) -> str:
    if label == "team_left":
        return "team_right"
    if label == "team_right":
        return "team_left"
    return label

df_h2["label"] = df_h2["label"].map(flip_lr_label)

df_match = pd.concat([df_h1, df_h2], ignore_index=True)

print(df_match["label"].value_counts())

label
team_left     726
team_right    712
goalkeeper     53
Name: count, dtype: int64

In [12]:
embeddings = extract_all_models(
    df_match=df_match,
    game_id=base_game,
    device=device,
    model_names=["osnet", "dino", "dinov2_large", "fastreid", "prtreid"],
)

========================================
  модель: osnet
========================================

c:\Users\Denis\OneDrive\Документы\sk_sber_football\.venv\Lib\site-packages\torchreid\reid\models\osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)

Successfully loaded imagenet pretrained weights from "C:\Users\Denis/.cache\torch\checkpoints\osnet_x1_0_imagenet.pth"
computing embeddings

  0%|          | 0/12 [00:00<?, ?it/s]c:\Users\Denis\OneDrive\Документы\sk_sber_football\Football_Skoltech\models.py:24: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=self.device == "cuda"):
 67%|██████▋   | 8/12 [02:05<01:02, 15.65s/it]

KeyboardInterrupt:

### Metrics

In [ ]:
df_report = compare_models(embeddings)

df_classification = df_report[[
    "lr_accuracy",
    "lr_macro_f1",
    "mlp_accuracy",
    "mlp_macro_f1",
    "macro_f1_delta_mlp_minus_lr",
    "best_lr",
    "best_mlp",
]].copy()

df_clustering = df_report[["cluster_acc", "cluster_macro_f1", "sil_euclidean", "sil_cosine"]].copy()
df_clustering = df_clustering.rename(columns={
    "cluster_acc": "kmeans_acc",
    "cluster_macro_f1": "kmeans_macro_f1",
    "sil_euclidean": "kmeans_sil_euclidean",
    "sil_cosine": "kmeans_sil_cosine",
})

print("Classification comparison: Logistic Regression vs 2-layer MLP")
display(df_classification)

print("Clustering metrics (k-means)")
display(df_clustering)

evaluating osnet...
evaluating dino...
evaluating dinov2_large...
evaluating fastreid...
evaluating clip...

              accuracy  macro_f1  cluster_acc  sil_euclidean  sil_cosine best
model
osnet           0.9691    0.9477       0.7479         0.1122      0.2066    +
dino            0.9725    0.9320       0.7431         0.1173      0.2129
fastreid        0.9622    0.8819       0.6605         0.0946      0.1665
dinov2_large    0.9656    0.8292       0.4401         0.0687      0.1203
clip            0.9588    0.7060       0.7342         0.1234      0.2196

### Visualization

In [ ]:
viz_cols = [
    "crop_path", "game", "frame_idx", "player_id",
    "x1", "y1", "x2", "y2", "source_folder", "image_file",
]

df_viz = df_match[[c for c in viz_cols if c in df_match.columns]].reset_index(drop=True)

name = "osnet"
X, y = embeddings[name]

interactive_embedding_view(
    X=X,
    y=y,
    df=df_viz,
    method="umap",
    sample_n=None,
    preload_images=True,
)

Снижение размерности (UMAP) для 1452 точек...

d:\Anaconda\envs\footpass\Lib\site-packages\umap\umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

Готово.
Кодирование изображений...
Готово.

HBox(children=(FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
   …

FigureWidget({
    'data': [{'customdata': array([['team_left', 'game_40_H1', '162', '202',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDY1uzkvbDbBrA0uZXDK7FfnAByvzcf/qpYZImtYzHcxzYVQSkgfHHcisjx7pk194XnuY4YZxakylJWwMBTnGO//wBes34Kf8I5qPw1NzZ2c9tqwlBnlMfyOR1QNnBxnivjaOHVSi5nNSpxlBs6okUUzODRXntanG9x0s6mya2nXfbOSZVx1BGCK850jUC3xAtNN0aL7DpUMEkS2KE4Zhg+Yc8k13L3M1lc/Z7uCS3m7LIMZ/8ArVwFtePqGo6xeeGbG2XW7CQ+bBO+MKfvbSc55HT6+1ejgJ3jKB00Z2jY9G+ZOH60VieGtf8A7Zt2DadeQ3MSqZ0eNlwTnpnqODzRXJOg+Ywa1PTI1W/8GTy3wF1JHCQjzDeVGOxPSvnzwsqxfEjUfKUJutAW2jGTv6miitMFvP0Ihueu+HUT+0r9tq58q25x/sGiiitGaH//2Q=='],
                                   ['team_left', 'game_40_H1', '162', '203',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAmABYDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDSmu9IhsJ4NTWZPOAVJ43KGM/Ucj8Kbp81vcWyvbSeZGMgNnPT371X8S6Tc6roF5BaXVtYSBf9fccqO2fb8PWq/gG28PaboEWkpq66pqsAw0lvKfL685Un618Th6calBvqjgpxUqZsFaKmZcniiuRpIxsY3ja7TTvDVze3Yl+yohZmQjPUDHNeY/BvUIj4kluLDS9QS2ugVM8mCg6nrnjpjgV2/jSLXoHGp6Y0NzbwqWmtZUDbl28gA8H8arapq3iiTQrPVtD0OxhtoY988P2RMsMjIBHAI56Ht+FetgOVUJLqaUH7rO6J6Y9KKxfDfiKw1/Sbe+gZkEkYYqyn5T0I/A5orzalOSk7ols1AqtlWAIxyCoYEfQ9abeXmp3Yjtme38tQFVAm1QM9MAUUVWDk0Kk9DI1bxFpVlJBo1rpX2RoEZme3+Xfk55wf9qiiinUb5mSf/9k='],
                                   ['team_left', 'game_40_H1', '162', '205',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAdABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDH8WPoWk3lve/2ZIyhhuQS9ufat+wl0O7tlmh0BVVgDhpWBrk/irLY2sFvPNeRwyqQqo4JDZ5re8IaguoaRDKI1Q4xgV8xKklT5jz7Wjc1PL0r/oAgf9vLUVYKA9hRXBzGfOcj4otba68TW0PiC3RtOddscocDy2Pbn72Tz9BUFxqFp4QvUiWyuG053wLhMCJGPQH0Nehafqtvp5dxpsE820hXmw2w+oBHXGR+NVxbQa/dfZ9RhjaK6ceaqLtzk549DW8cS3DlY1NpWIYLiOaFZFwQR2bp7UVqa4ul2mpSWtppiwwwgIqhwc479KKwsiLn/9k='],
                                   ...,
                                   ['team_left', 'game_40_H2', '138968', '204',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCPFJcTRWtrLdTbliiUu5AJwPWlHWsnxXq2l2FvHbamkk1vMcTxxjJ2EdcflXx2HourOyPPhFzlZGPpXj211LUlgtbfFvkqZSCTjIG7HpXYyHa5UfMM9RXM6RaeG7XWLeHwtpEE9ktvk3RBB5IPPXnpxmunyo6YP0GK3xcFT0R0V6cYaDCSeADRTt3FFcdzlIJJAsbMTyB8o9TXnHjy38Q6Jv1/UIIWTViYbREuFZkQAryO3HX3rZ+JiySWdtCkjIqv5jFWwcjpzXnpl1jVWa91nUpr5kfy7bzTnYncD05xxX0OUYSKh7ZbnTh42fMb/gXVE8MWNnb2QmvrbUQI7gl9i20+QMHg5HXngV6pJb3VrMY5/LbA6pIGHU9x346VzXw5gitPCXkR3EksdzNJJJE4yM7iMc/St63iWBRFABHF2XrXnZnNOo0ugV3eTJdx6c0UmKK8tXOYxvFWh3+q6XKbCS3aQgoI3k2uPcDvXlEBngafQWi239mGOwn/AFgB5KnHP/1q9ugtjcXSJnknA5rhfi/Do32mGK4kurfWLcgw3EAHAHRSe+f6V7+W4lxfIzopVOVWKfww1C/itbySeGb+yhL8sxjO1X7r06/j2r0aF1eNXQ5VhkGvG9F8eXul3YsNVuLqbQZLhJruxjbCTlWyc/Xr+FexHVvDurQx3fh9JY4ZFD7Gj2gZ5rLN6CjUc11HXScOckz70VFub3orxrnEm2SAkHg8+1cn8Sxol3ZLCbaOTU5yqeYRkhAR/kV1eaqu9vDOs3/CPWNyyn70sjZP6114esoblmLo/hfwvbWYD6dBcXBAYu6clu+a1I0t7WICCGONB0UHH5Cr9xqCXSiN/C+kWQ4PmRMzP9OTj9K2fhkNFuPiFptnq9qJrdlkZF8sEhgOMmtISeIqKEnox76HPpcFZESW3uIC43J5kRUMPUHvRXt/x6n8LTeGRM0GdQVx9leOPaVORnJx0welFcWIpezqOK1Fy2P/2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '210',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAgADQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDgV+I+nXrH7Pp8r4HUQSCptE8WXuo3UiR6avlIMkqGZgPoK5LxTeyaPeR/ZVRULfcKghh1x+VTRweO5Y49T8LmDTVlTEhtpQN3Xkrg57c9axjToxg20aOEeXY9YTftBeJoyezDFKelZXgfR9fi0y4udd1M3t0cOxZlLYx3x+VaP2iEkr5q5BxjPevmMUl7T3TyqkUmOoPSlcbcH1pM8VzWsyCMiinUUrsk8w1/4favqWoGVdSUQMQwDMBtwT6D04rtdE03+w9KSyjuBMEHBxVW7m1S7ZZJXWFeCYol4/M81dhuIls1iEchmHUseDXqVMS5Q5bnoutaNhZ0M3L3NwintHj+oqr4b8L6bY61FqEs09ziTfh/dsn/APX71ciMzLzZqffcaswG4B+4sePTP9a4VNxZxVHc7rXrvRDo8cSxRxz4+QJzgdq5HgNx0qvDG4YvIxYnrU+ewFZzld3JHUUnFFZi5T//2Q=='],
                                   ['team_left', 'game_40_H2', '138968', '213',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCABXAEkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCgPvU7I9aRRzR5Z67vwr87ueeLmhGBNAA6Uu1RyKTYEgIxQSCKjyacGTBLHhQSecVUYuTshpXIp5obaJp7mRI4l6s7YH615Zq/xO1Z76b+zhAtjGx271X51B9Sa6DxLrcV7bbZNFuks9zbZ5XG1iP4sDsK8zTw1eapcW9jpx8552LMMEBFB5P5Y/OvoMFgUoc1RGkad1dnvWj3keo6VaaggIW4iWQAkZ5+lXd9VLCyTT9NtbCPAjt4VjGPUDn9an2+5rw69vaPl2MnoMDU5WzTHQqaVOnWsbpsFqLkAnigN2xTqQ8UXQB+IHuawE8YW914kSytLP7VYaahnuWiG5ribcBHEmO+QeOc5reQO7bDGGVvlOc4x74rgpvE/hnwXourWugCO5168mcR5YSKmdoLAgAZHOB1r3clwyrVNTanHUq+Pre1TxRqktpeQaZbwylDYXUhZlYoGYjHA64IPINa3w1uYpLCz1JIxFNIskKPwfMQemM1zGk+E5fGHjvS/ClpLM5SMS3rrueSU5DPzngndjJ6cV6pqWiaFp3iiSHQo7m3tLGMW6wyShxvHDHoMemPY+tfTZpCGHw0o91ob1UoxJnbdTNvv+tO2nOM07Z71+enFcQnPWotpLcY/OpMUjZC5Ubj6ZqVoCHZGKZL9w84x3zUavOWwbfA9d4qV1UxsGHBU5pWA5jx/qU1jpqaUGltDfHa9yRjCY/hJ78mvK7jT7ZLgeQQAhGDnr7/AI11/wAR9VuLPxZdaNqsL3WiTxRyLkjdAw/iUn3HT3rlZ9PAi8/SNXtb6HklMEPGM8Bs9/cV9vldBUqMZR6nXSsjU8KXtrJ4ylu7jUZLG6ZCIXR9nPygYOfb9K9g0/ZIg+zK0+FeSaTeMjuWPt7+1eA2Oo6BcXn2HV9OkV3Pl/aI3A8thzur2v4b6N4q0nxTa3Vi51XTPs8nlhYid+5MJz0PPY/XvW2buNakozdrGlfVGwdrKrqcqwyCD1FJtHr+tdDY/DPxJcGW71jU7PSonkZ9suCVU89M1N/wgWg/9D7ZfkP8a+J9nI89nMKQVyaaZF3qg5ZjhVzgk+greT4feLp49101jpqEcGRyTnsMV1Oh+HvD/gLSbrxB4h1OLUtTjiIi3IRHE2M4wffjNbUcNKoxnn19FLYusd7byWrkBgsowSD35qCIT3MghtbdpixCgofWsvx18TYdJlW50ezbUr2QtLJcyWwliQf3Rk5H8ua5rRP2j/EcMsiXdjpCA5ACWgHHp069e9d9PKZze6KgrnP/ABAt9cvPFN1LcwQ2gGIU88gEKOMkA9O9clNoGrx2Nxr2nyLc2sEmyaaHIEbYzznGB9a2/Egj8ZX9xry3hjurh8+QxY/MegAHCj9K9V+H/hqLQfB39j3GyYXQc3B28OGAHQ969v6wsLTjFnRsrnk3hbWrKHWbfU9Tt7e7t9MXz3TYu6ZeOOeCeP1r2L4bfE7xH4g8MSG1uYNNUTOjeTEisw9Dgc8GuC+IvgO50vSp20W6t1sbpgZwU2yZz0yOMdKf8M717GX+zI4MeaoLbSMKe5pY+tDEUOZdBzlzRPRL97m9I+2X1xckdpJCw/LtVb7Ba/8APGP/AL5qwMZ60YFfIyk7nEX7W4vpb1Zb/VLq4YkDzJZSdvOeOwp3iLWbjWbqK0AxptumFjdeZH6F29TkZrPycYzSdORWscVKKsiiSRrcJ5bWsDKBjBjHNc5rngLwlrCmQ2H2S4bOJImwAe2R3HtW2xycnmm+aQSKqGLq03dMcXynL6R8O9L0q7juDeTXXksGj/hAIORXWR7+8jn0BNQvMcYpqSMRkdKiriZ1pXZXM2cr8VrzVbTS4GtIpJrczbpjjIA9P8+tUPhdIs/269a3aNml2KWOc4A5HpUfxdvZpLG20+GRdzSq2wN82SfStzwRpjWPhu3Xqz5kb6nH+Fer7RxwdmVzWVjohKQaXzDVZd+af83pXitXMS9QelFFYrcYwrkmgRqeTRRW7YCiJc9AaMZG0IuzIHHGaKKdBXmiloUtX8JfDm8sU1zU7PVpJkGDDFdlWZj7lSODz1HWl0UvqMSw6Vo8tnbqNsaTTq7gfUH0oor6vMKEFhFZEsutY3FrJ5d0gR8ZxkH+VGxfQUUV8kB//9k=']],
                                  shape=(705, 5), dtype=object),
              'hovertemplate': ('<b>%{customdata[0]}</b><br>gam' ... 'argin-top:4px"><extra></extra>'),
              'marker': {'color': '#3b82f6', 'line': {'width': 0}, 'opacity': 0.75, 'size': 6},
              'mode': 'markers',
              'name': 'team_left',
              'type': 'scatter',
              'uid': '2a73964a-e7b2-45da-9eaa-ed7713abfeee',
              'x': {'bdata': ('FqFlwLlqcsB4DVjALUTkvwvdesDMrY' ... '/qv7G8EsA+K7e/KzEBwI6DbsDckcG/'),
                    'dtype': 'f4'},
              'y': {'bdata': ('+pTcQJmb7ECu08JAg7f6QKNO6kDq+w' ... 'QEQaKm/0DC4B1BZJMVQYe57UAlRANB'),
                    'dtype': 'f4'}},
             {'customdata': array([['team_right', 'game_40_H1', '162', '101',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAyABwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCasXxjr13omh3Fzphja8VR5YYZC89a2hu/hGfSuk0nwL4fv/Dc954jmZludyFNwVY19/evzSnU5aiuZYDBPE1eVHm/w98Q6x4i064n1doGmjcDegCjp0wK6ZeRniuYb4aW3hzU7i20nxFcGBz5gCNt4J4/HGAa6ZY1RQgLtgYz6/rXVi5U5TvAWNpKhU9n2FgUtKqjG4nAzUHhi31fxNd30Ul2ZNGs7toRDGWB3jkknPIz7GlkkVM5PavUf2bbPSfEXgSe5RcFdQmDYypIDHBI7GuvA5VPFUZ1I9D1MixywlVza0scL4ogjt9XZYJE2LGilVHfHXPWszPvXT/F7R00Lx3JDCZPJvIROu4ZwQcEZrki+OCK8p05QbUuh5WY1/rGIlU7lVrlZtSWxiRnc5JwpwgAJJJ7DArY+G3xPutGjutD8NaZE9nHIDJeNDtjDhcMPVgSBz703UrqZPCU2nWFhHnUiqvdgASxKsgyFbqMgY46gmse0tYtNgEMUa+VgZHAJr3MHjZYSEoQ2Z1YarSpQ95as1tY+JN743uwl9DBCtozpxHyDuxt3dxxxVFpck8ZqofDN1p11I9pJDc/apN8VrE/7xRwc8/eA6ZHerLRTRHy5oTHIOqscEV5+LhzSuTmUY+1vBaMhEkmUHmPgA456ZzmnyANHJu5wOM0UUl0PNnsjn7aabz3fzZNw43bjnGRxXU2jM1urMxYkdSaKKuvudNXZH//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '102',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAiABQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDb0jTpo5J9f1tpYtChiceWi/PI46HPXGfSqsMizRLIh3Ajg4r0fTru2uNO023MweyhsCLuPy872OePwwenrXnUECPZtdWc6yWgO1SxAYegx17V+Zps2zHBwpYanOK33GkZPWikDZGeaKR85zI6n4VXNrea0+mX11HatFG8qOxUeYueV+b0H86f8VNC8P6TdafqGhMqCQGOeNT8hyAyuOcDPPFcZDpM13exfZoxLcDcUBBx0J59uMfjV528RzaJaS6tZWvl3DEk2zl3QjorLklQBx74FepSUJUGranv+2eIw/JUeyK7SAnJAoqPZIONpHsRRXH7M8XkRo+H3dNat9jsv3hwcfwmsjSLq5S9ukS4mVSeQHIB5oorWj8B20/4bLM7MZWyx6+tFFFQcR//2Q=='],
                                   ['team_right', 'game_40_H1', '162', '103',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAAsABkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwC2KKSrWi2y6lq8OnicRPIf7pYkDr06fXpX5YeZSpSnUUV1GaU3hW5ZU1G+ma8n/wCPVLcdP97nn8Kk8iP+9+tdh8RNG8Pw6KFtoYbe6gC+XtUBscbgMeuK4TzhV6dj2cXl6pOKfVDd4HrXSeD9Nn0/Tb/xDMgMkqNFanH3cYya57X9d8IWVk5sND1m9utgKlbnMbHJzjHUYx+ddr8LPE3gvX/B1npGs6itpdbnYwnIcE/gcdO9dNPBzqWsLK1GlVVSeyOUub/U9atI3FnJOVwsjRKRgjjGOQPpVLY//PI12/xdtv8AhGtbtDpEy/Yb+Le4AHDjA6jA5HWuG+1P6N+VTiaEsPLkkGaZg8RXcloloVFOCVPKnoCBVbV9M1m90y7udA8OteT2ao4eAAOcnB6deKu7R1xTbbX9S8NSrfaZMFkPLK+SjYPGRnmihUcZpnDSryg1bY5/wjPeXlug1E3X2qPqs0jNt+meg4/Sujwf7/6VW1fxTqWv3K3l5HZxyqhXNvbrHkcdcdaxf7UuvVPyqq8+ebcjkq1m6kmf/9k='],
                                   ...,
                                   ['team_right', 'game_40_H2', '138968', '110',
                                    '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAA/ACwDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwCm2iQjgajZ/hIKP7HixzqFngf7Yqj9mhAx5a/lR5EP/PNc/Svj+dnm3LE1np1uGkmvIyqAligBwB+Neb3viDXLvxAbTTLoQwebsQRbXyn98+h9q9O8P+D9S8W3cttbS/YrKMYlnMWc+q4PWqHj7wJB4Y8hfDMcNxcMCJ3bClJATk8dK3pTjH4up7mDy2VSi6kh2n2duYAt5qcazDqxUgk1oJp2k7Ru1qEH0I/+tWNpUN4LOMakQ1x/HhsirohQD7o/KsW3zM8Oqnzuw/GaAADknin7amtNNXVZ47FppIRK4UumOBn3rnnU5VdmlCn7Waiuo+y8QeKolaw8OlILRD+8naQYJI54POap3C3dvcs2parDcXNxiQl5FDNxxgDv9efWty+0gaXez21ldGS2QnczgAtjI4/TpXJQaVbT3kmpS2rqd7JG8qkAgdcE9ef506MpVVzdEfoWYSjgsuUbas0tpz9yQDsWXFOCnFKZZGQRl2KAcA08YxVXPzeUm3cS0sNb1G3vLzT9OkntbQ4lYKeecYHqarRahLbSeZG7QXETfMCdpXnBBzW/D471eys4rDSNPt4baJgr7yymVgOWbB7nkVy2sa3dSLfXWq6Da3jTyDyiobK5bLMcY6c/WnFxckehRoRaUlKzPePDXwvtNbh03XJNSnWOSOKbYu0qcrk+vfirHxtXwvH4aXRppkF5blTbxKMlGx1OeQP0ryLw3+0Df+HsaTpmlQXGnwxkRtclkdSOAMDAAriTf6t4j8V3nieazt4bzUZy88SMfLHPBXngfievWvaxNal7FQpo9LEVK1aCjOV0jpIkwoBOamCUxNwUB1AbuBUgfArwXufPPSTQxQB2pCwQ5x06UMcCozLGOWOB9KSeoouxma0NCkGdRg/eDkMkfP4kVLpEVrFGv2V5GjI4yoAxXUw+IfhyLNrTVLW5mlJwz+Wx2nGD0IzWPdy+GXm/4p661AxDIMc8QVQPUY5+g/M1rJ2Wh6NTEXpKK3HCl59Kb0PNLvWsjzNWz//Z'],
                                   ['team_right', 'game_40_H2', '138968', '112',